# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app4.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets 

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1044, 936)
       
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setObjectName("tabs")
        self.StudentInfo = QtWidgets.QWidget()
        self.StudentInfo.setObjectName("StudentInfo")
        self.formLayout = QtWidgets.QFormLayout(self.StudentInfo)
        self.formLayout.setObjectName("formLayout")
        self.stunamelbl = QtWidgets.QLabel(self.StudentInfo)
        self.stunamelbl.setMinimumSize(QtCore.QSize(171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stunamelbl.setFont(font)
        self.stunamelbl.setWordWrap(True)
        self.stunamelbl.setObjectName("stunamelbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.stunamelbl)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 99, -1)
        self.horizontalLayout.setSpacing(96)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stunamebox = QtWidgets.QLineEdit(self.StudentInfo)
        self.stunamebox.setMaximumSize(QtCore.QSize(221, 31))
        self.stunamebox.setObjectName("stunamebox")
        self.horizontalLayout.addWidget(self.stunamebox)
        self.label = QtWidgets.QLabel(self.StudentInfo)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton_2 = QtWidgets.QPushButton(self.StudentInfo)
        self.pushButton_2.setMinimumSize(QtCore.QSize(93, 28))
        self.pushButton_2.setMaximumSize(QtCore.QSize(93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.stunamelbl_2 = QtWidgets.QLabel(self.StudentInfo)
        self.stunamelbl_2.setMinimumSize(QtCore.QSize(161, 61))
        self.stunamelbl_2.setMaximumSize(QtCore.QSize(161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stunamelbl_2.setFont(font)
        self.stunamelbl_2.setWordWrap(True)
        self.stunamelbl_2.setObjectName("stunamelbl_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.stunamelbl_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stunameexist = QtWidgets.QLineEdit(self.StudentInfo)
        self.stunameexist.setMaximumSize(QtCore.QSize(221, 31))
        self.stunameexist.setObjectName("stunameexist")
        self.horizontalLayout_2.addWidget(self.stunameexist)
        self.pushButton = QtWidgets.QPushButton(self.StudentInfo)
        self.pushButton.setMinimumSize(QtCore.QSize(93, 28))
        self.pushButton.setMaximumSize(QtCore.QSize(93, 28))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.StudentInfo)
        self.pushButton_3.setMinimumSize(QtCore.QSize(93, 28))
        self.pushButton_3.setMaximumSize(QtCore.QSize(93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 25, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.elaacclbl = QtWidgets.QLabel(self.StudentInfo)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.elaacclbl.setFont(font)
        self.elaacclbl.setObjectName("elaacclbl")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.elaacclbl)
        self.elaaccbox = QtWidgets.QTextBrowser(self.StudentInfo)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.elaaccbox.setFont(font)
        self.elaaccbox.setObjectName("elaaccbox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.elaaccbox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.mathacclbl = QtWidgets.QLabel(self.StudentInfo)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mathacclbl.setFont(font)
        self.mathacclbl.setObjectName("mathacclbl")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.mathacclbl)
        self.mathaccbox = QtWidgets.QTextBrowser(self.StudentInfo)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mathaccbox.setFont(font)
        self.mathaccbox.setObjectName("mathaccbox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.mathaccbox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.sciacclbl = QtWidgets.QLabel(self.StudentInfo)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sciacclbl.setFont(font)
        self.sciacclbl.setObjectName("sciacclbl")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.sciacclbl)
        self.sciaccbox = QtWidgets.QTextBrowser(self.StudentInfo)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sciaccbox.setFont(font)
        self.sciaccbox.setObjectName("sciaccbox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.sciaccbox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(8, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        self.ssacclbl = QtWidgets.QLabel(self.StudentInfo)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ssacclbl.setFont(font)
        self.ssacclbl.setWordWrap(True)
        self.ssacclbl.setObjectName("ssacclbl")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.ssacclbl)
        self.ssacbox = QtWidgets.QTextBrowser(self.StudentInfo)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ssacbox.setFont(font)
        self.ssacbox.setObjectName("ssacbox")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.ssacbox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(10, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        self.wlacclbl = QtWidgets.QLabel(self.StudentInfo)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.wlacclbl.setFont(font)
        self.wlacclbl.setWordWrap(True)
        self.wlacclbl.setObjectName("wlacclbl")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.wlacclbl)
        self.wlaccbox = QtWidgets.QTextBrowser(self.StudentInfo)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.wlaccbox.setFont(font)
        self.wlaccbox.setObjectName("wlaccbox")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.wlaccbox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(12, QtWidgets.QFormLayout.LabelRole, spacerItem5)
        self.enlacclbl = QtWidgets.QLabel(self.StudentInfo)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.enlacclbl.setFont(font)
        self.enlacclbl.setObjectName("enlacclbl")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.enlacclbl)
        self.enlaccbox = QtWidgets.QTextBrowser(self.StudentInfo)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.enlaccbox.setFont(font)
        self.enlaccbox.setObjectName("enlaccbox")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.enlaccbox)
        #self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        #self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        #self.deletenamecombo = QtWidgets.QComboBox(self.StudentInfo)
        #self.deletenamecombo.setMaximumSize(QtCore.QSize(200, 26))
        #self.deletenamecombo.setObjectName("deletenamecombo")
        #self.horizontalLayout_3.addWidget(self.deletenamecombo)
        #self.deleterec = QtWidgets.QPushButton(self.StudentInfo)
        #self.deleterec.setMaximumSize(QtCore.QSize(120, 26))
        #self.deleterec.setObjectName("deleterec")
        #self.horizontalLayout_3.addWidget(self.deleterec)
        #self.sure = QtWidgets.QLabel(self.StudentInfo)
        #self.sure.setWordWrap(True)
        #self.sure.setObjectName("sure")
        #self.sure.setMinimumSize(QtCore.QSize(93, 33))
        #self.horizontalLayout_3.addWidget(self.sure)
        #self.deleterecordchk = QtWidgets.QCheckBox(self.StudentInfo)
        #self.deleterecordchk.setObjectName("deleterecordchk")
        #self.horizontalLayout_3.addWidget(self.deleterecordchk)
        #self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.tabs.addTab(self.StudentInfo, "")
        self.elatab = QtWidgets.QWidget()
        self.elatab.setObjectName("elatab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.elatab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.elagrpbx = QtWidgets.QGroupBox(self.elatab)
        self.elagrpbx.setMinimumSize(QtCore.QSize(994, 812))
        self.elagrpbx.setTitle("")
        self.elagrpbx.setObjectName("elagrpbx")
        self.formLayout_3 = QtWidgets.QFormLayout(self.elagrpbx)
        self.formLayout_3.setObjectName("formLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout_2.setObjectName("formLayout_2")
        self.elaname = QtWidgets.QLineEdit(self.elagrpbx)
        self.elaname.setMaximumSize(QtCore.QSize(78, 20))
        self.elaname.setObjectName("elaname")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.elaname)
        self.label_35 = QtWidgets.QLabel(self.elagrpbx)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.elaexp = QtWidgets.QLineEdit(self.elagrpbx)
        self.elaexp.setMaximumSize(QtCore.QSize(78, 20))
        self.elaexp.setObjectName("elaexp")
        reg_ex = QtCore.QRegExp("[0-9]+.?[0-9]{,2}")
        input_validator = QtGui.QRegExpValidator(reg_ex, self.elaexp)
        self.elaexp.setValidator(input_validator)
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.elaexp)
        self.elaaddnew = QtWidgets.QPushButton(self.elagrpbx)
        self.elaaddnew.setMaximumSize(QtCore.QSize(75, 23))
        self.elaaddnew.setObjectName("elaaddnew")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.elaaddnew)
        #self.eladel = QtWidgets.QPushButton(self.elagrpbx)
        #self.eladel.setMaximumSize(QtCore.QSize(75, 23))
        #self.eladel.setObjectName("eladel")
        #self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.eladel)
        self.eladate = QtWidgets.QDateEdit(self.elagrpbx)
        self.eladate.setCalendarPopup(True)
        self.eladate.setMaximumSize(QtCore.QSize(95, 22))
        self.eladate.setMinimumDate(QtCore.QDate.currentDate())
        self.eladate.setObjectName("eladate")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.eladate)
        self.label_33 = QtWidgets.QLabel(self.elagrpbx)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.label_34 = QtWidgets.QLabel(self.elagrpbx)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setWordWrap(True)
        self.label_34.setObjectName("label_34")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.label_36 = QtWidgets.QLabel(self.elagrpbx)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.elaact = QtWidgets.QLineEdit(self.elagrpbx)
        self.elaact.setMaximumSize(QtCore.QSize(78, 20))
        self.elaact.setObjectName("elaact")
        reg_ex = QtCore.QRegExp("[0-9]+.?[0-9]{,2}")
        input_validator = QtGui.QRegExpValidator(reg_ex, self.elaact)
        self.elaact.setValidator(input_validator)
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.elaact)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout_2)
        self.elatable = QtWidgets.QTableWidget(self.elagrpbx)
        self.elatable.setMinimumSize(QtCore.QSize(729, 600))
        self.elatable.setMaximumSize(QtCore.QSize(729, 619))
        self.elatable.setObjectName("elatable")
        self.elatable.setColumnCount(4)
        self.elatable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.elatable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.elatable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.elatable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.elatable.setHorizontalHeaderItem(3, item)
        self.elatable.horizontalHeader().setDefaultSectionSize(175)
        self.elatable.verticalHeader().setCascadingSectionResizes(False)
        self.elatable.verticalHeader().setDefaultSectionSize(46)
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.elatable)
        self.elacalculate = QtWidgets.QPushButton(self.elagrpbx)
        self.elacalculate.setMinimumSize(QtCore.QSize(93, 28))
        self.elacalculate.setMaximumSize(QtCore.QSize(93, 28))
        self.elacalculate.setObjectName("elacalculate")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.elacalculate)
       # self.elaupdate = QtWidgets.QPushButton(self.elagrpbx)
       # self.elaupdate.setMinimumSize(QtCore.QSize(93, 28))
       # self.elaupdate.setMaximumSize(QtCore.QSize(200, 28))
       # self.elaupdate.setObjectName("elaupdate")
       # self.elacheckBox = QtWidgets.QCheckBox(self.elagrpbx)
       # self.elacheckBox.setGeometry(QtCore.QRect(10, 530, 521, 20))
       # self.elacheckBox.setObjectName("elacheckBox")
       # self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.elaupdate)
        self.elaresult = QtWidgets.QTextBrowser(self.elagrpbx)
        self.elaresult.setMaximumSize(QtCore.QSize(621, 101))
        self.elaresult.setObjectName("elaresult")
        self.elaresult.setFontPointSize(12)
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.elaresult)
        self.verticalLayout_9.addWidget(self.elagrpbx)
        self.tabs.addTab(self.elatab, "")
        self.mathtab = QtWidgets.QWidget()
        self.mathtab.setObjectName("mathtab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.mathtab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mathgrpbox = QtWidgets.QGroupBox(self.mathtab)
        self.mathgrpbox.setTitle("")
        self.mathgrpbox.setObjectName("mathgrpbox")
        self.formLayout_5 = QtWidgets.QFormLayout(self.mathgrpbox)
        self.formLayout_5.setObjectName("formLayout_5")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout_4.setObjectName("formLayout_4")
        self.mathname = QtWidgets.QLineEdit(self.mathgrpbox)
        self.mathname.setMaximumSize(QtCore.QSize(78, 20))
        self.mathname.setObjectName("mathname")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.mathname)
        self.label_37 = QtWidgets.QLabel(self.mathgrpbox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.mathexp = QtWidgets.QLineEdit(self.mathgrpbox)
        self.mathexp.setMaximumSize(QtCore.QSize(78, 20))
        self.mathexp.setObjectName("mathexp")
        reg_ex = QtCore.QRegExp("[0-9]+.?[0-9]{,2}")
        input_validator = QtGui.QRegExpValidator(reg_ex, self.mathexp)
        self.mathexp.setValidator(input_validator)
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.mathexp)
        self.mathaddnew = QtWidgets.QPushButton(self.mathgrpbox)
        self.mathaddnew.setMaximumSize(QtCore.QSize(75, 23))
        self.mathaddnew.setObjectName("mathaddnew")        
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.mathaddnew)
        #self.mathdel = QtWidgets.QPushButton(self.mathgrpbox)
        #self.mathdel.setMaximumSize(QtCore.QSize(75, 23))
        #self.mathdel.setObjectName("mathdel")
        #self.formLayout_4.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.mathdel)
        self.mathdate = QtWidgets.QDateEdit(self.mathgrpbox)
        self.mathdate.setCalendarPopup(True)
        self.mathdate.setMaximumSize(QtCore.QSize(95, 22))
        self.mathdate.setMinimumDate(QtCore.QDate.currentDate())
        self.mathdate.setObjectName("mathdate")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mathdate)
        self.label_38 = QtWidgets.QLabel(self.mathgrpbox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.label_39 = QtWidgets.QLabel(self.mathgrpbox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setWordWrap(True)
        self.label_39.setObjectName("label_39")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.label_40 = QtWidgets.QLabel(self.mathgrpbox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.mathact = QtWidgets.QLineEdit(self.mathgrpbox)
        self.mathact.setMaximumSize(QtCore.QSize(78, 20))
        self.mathact.setObjectName("mathact")
        reg_ex = QtCore.QRegExp("[0-9]+.?[0-9]{,2}")
        input_validator = QtGui.QRegExpValidator(reg_ex, self.mathact)
        self.mathact.setValidator(input_validator)
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.mathact)
        self.formLayout_5.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout_4)
        self.mathtable = QtWidgets.QTableWidget(self.mathgrpbox)
        self.mathtable.setMinimumSize(QtCore.QSize(729, 600))
        self.mathtable.setMaximumSize(QtCore.QSize(729, 619))
        self.mathtable.setObjectName("mathtable")
        self.mathtable.setColumnCount(4)
        self.mathtable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.mathtable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.mathtable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.mathtable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.mathtable.setHorizontalHeaderItem(3, item)
        self.mathtable.horizontalHeader().setDefaultSectionSize(175)
        self.mathtable.verticalHeader().setCascadingSectionResizes(False)
        self.mathtable.verticalHeader().setDefaultSectionSize(46)
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mathtable)
        self.mathcalculate = QtWidgets.QPushButton(self.mathgrpbox)
        self.mathcalculate.setObjectName("mathcalculate")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.mathcalculate)
        #self.mathupdate = QtWidgets.QPushButton(self.mathgrpbox)
        #self.mathupdate.setMinimumSize(QtCore.QSize(93, 28))
        #self.mathupdate.setMaximumSize(QtCore.QSize(200, 28))
        #self.mathupdate.setObjectName("mathupdate")
        #self.mathcheckBox = QtWidgets.QCheckBox(self.mathgrpbox)
        #self.mathcheckBox.setGeometry(QtCore.QRect(10, 530, 521, 20))
        #self.mathcheckBox.setObjectName("mathcheckBox")
        #self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.mathupdate)
        self.mathresult = QtWidgets.QTextBrowser(self.mathgrpbox)
        self.mathresult.setMaximumSize(QtCore.QSize(621, 101))
        self.mathresult.setObjectName("mathresult")
        self.mathresult.setFontPointSize(12)
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.mathresult)
        self.verticalLayout_6.addWidget(self.mathgrpbox)
        self.tabs.addTab(self.mathtab, "")
        self.sstab = QtWidgets.QWidget()
        self.sstab.setObjectName("sstab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.sstab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.ssgrpbox = QtWidgets.QGroupBox(self.sstab)
        self.ssgrpbox.setTitle("")
        self.ssgrpbox.setObjectName("ssgrpbox")
        self.formLayout_7 = QtWidgets.QFormLayout(self.ssgrpbox)
        self.formLayout_7.setObjectName("formLayout_7")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout_6.setObjectName("formLayout_6")
        self.ssname = QtWidgets.QLineEdit(self.ssgrpbox)
        self.ssname.setMaximumSize(QtCore.QSize(78, 20))
        self.ssname.setObjectName("ssname")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ssname)
        self.label_41 = QtWidgets.QLabel(self.ssgrpbox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.ssexp = QtWidgets.QLineEdit(self.ssgrpbox)
        self.ssexp.setMaximumSize(QtCore.QSize(78, 20))
        self.ssexp.setObjectName("ssexp")
        reg_ex = QtCore.QRegExp("[0-9]+.?[0-9]{,2}")
        input_validator = QtGui.QRegExpValidator(reg_ex, self.ssexp)
        self.ssexp.setValidator(input_validator)
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.ssexp)
        self.ssaddnew = QtWidgets.QPushButton(self.ssgrpbox)
        self.ssaddnew.setMaximumSize(QtCore.QSize(75, 23))
        self.ssaddnew.setObjectName("ssaddnew")
        self.formLayout_6.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.ssaddnew)
       # self.ssdel = QtWidgets.QPushButton(self.ssgrpbox)
       # self.ssdel.setMaximumSize(QtCore.QSize(75, 23))
       # self.ssdel.setObjectName("ssdel")
       # self.formLayout_6.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.ssdel)
        self.ssdat = QtWidgets.QDateEdit(self.ssgrpbox)
        self.ssdat.setCalendarPopup(True)
        self.ssdat.setMaximumSize(QtCore.QSize(95, 22))
        self.ssdat.setMinimumDate(QtCore.QDate.currentDate())
        self.ssdat.setObjectName("ssdat")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ssdat)
        self.label_42 = QtWidgets.QLabel(self.ssgrpbox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.label_43 = QtWidgets.QLabel(self.ssgrpbox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setWordWrap(True)
        self.label_43.setObjectName("label_43")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_43)
        self.label_44 = QtWidgets.QLabel(self.ssgrpbox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_44)
        self.ssact = QtWidgets.QLineEdit(self.ssgrpbox)
        self.ssact.setMaximumSize(QtCore.QSize(78, 20))
        self.ssact.setObjectName("ssact")
        reg_ex = QtCore.QRegExp("[0-9]+.?[0-9]{,2}")
        input_validator = QtGui.QRegExpValidator(reg_ex, self.ssact)
        self.ssact.setValidator(input_validator)
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.ssact)
        self.formLayout_7.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout_6)
        self.sstable = QtWidgets.QTableWidget(self.ssgrpbox)
        self.sstable.setMinimumSize(QtCore.QSize(729, 600))
        self.sstable.setMaximumSize(QtCore.QSize(729, 619))
        self.sstable.setObjectName("sstable")
        self.sstable.setColumnCount(4)
        self.sstable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.sstable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.sstable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.sstable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.sstable.setHorizontalHeaderItem(3, item)
        self.sstable.horizontalHeader().setDefaultSectionSize(175)
        self.sstable.verticalHeader().setCascadingSectionResizes(False)
        self.sstable.verticalHeader().setDefaultSectionSize(46)
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sstable)
        self.sscalculate = QtWidgets.QPushButton(self.ssgrpbox)
        self.sscalculate.setObjectName("sscalculate")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sscalculate)
        #self.ssupdate = QtWidgets.QPushButton(self.ssgrpbox)
        #self.ssupdate.setMinimumSize(QtCore.QSize(93, 28))
        #self.ssupdate.setMaximumSize(QtCore.QSize(200, 28))
        #self.ssupdate.setObjectName("ssupdate")
        #self.sscheckBox = QtWidgets.QCheckBox(self.ssgrpbox)
        #self.sscheckBox.setGeometry(QtCore.QRect(10, 530, 521, 20))
        #self.sscheckBox.setObjectName("sscheckBox")
        #self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ssupdate)
        self.ssreult = QtWidgets.QTextBrowser(self.ssgrpbox)
        self.ssreult.setMaximumSize(QtCore.QSize(621, 101))
        self.ssreult.setObjectName("ssreult")
        self.ssreult.setFontPointSize(12)
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.ssreult)
        self.verticalLayout_8.addWidget(self.ssgrpbox)
        self.tabs.addTab(self.sstab, "")
        self.scitab = QtWidgets.QWidget()
        self.scitab.setObjectName("scitab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scitab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scigrpbox = QtWidgets.QGroupBox(self.scitab)
        self.scigrpbox.setTitle("")
        self.scigrpbox.setObjectName("scigrpbox")
        self.formLayout_9 = QtWidgets.QFormLayout(self.scigrpbox)
        self.formLayout_9.setObjectName("formLayout_9")
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout_8.setObjectName("formLayout_8")
        self.sciname = QtWidgets.QLineEdit(self.scigrpbox)
        self.sciname.setMaximumSize(QtCore.QSize(78, 20))
        self.sciname.setObjectName("sciname")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sciname)
        self.label_45 = QtWidgets.QLabel(self.scigrpbox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_45)
        self.sciexp = QtWidgets.QLineEdit(self.scigrpbox)
        self.sciexp.setMaximumSize(QtCore.QSize(78, 20))
        self.sciexp.setObjectName("sciexp")
        reg_ex = QtCore.QRegExp("[0-9]+.?[0-9]{,2}")
        input_validator = QtGui.QRegExpValidator(reg_ex, self.sciexp)
        self.sciexp.setValidator(input_validator)
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.sciexp)
        self.sciaddnew = QtWidgets.QPushButton(self.scigrpbox)
        self.sciaddnew.setMaximumSize(QtCore.QSize(75, 23))
        self.sciaddnew.setObjectName("sciaddnew")
        self.formLayout_8.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.sciaddnew)
        #self.scidel = QtWidgets.QPushButton(self.scigrpbox)
        #self.scidel.setMaximumSize(QtCore.QSize(75, 23))
        #self.scidel.setObjectName("scidel")
        #self.formLayout_8.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.scidel)
        self.scidate = QtWidgets.QDateEdit(self.scigrpbox)
        self.scidate.setCalendarPopup(True)
        self.scidate.setMaximumSize(QtCore.QSize(95, 22))
        self.scidate.setMinimumDate(QtCore.QDate.currentDate())
        self.scidate.setObjectName("scidate")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.scidate)
        self.label_46 = QtWidgets.QLabel(self.scigrpbox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_46)
        self.label_47 = QtWidgets.QLabel(self.scigrpbox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_47.setFont(font)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setWordWrap(True)
        self.label_47.setObjectName("label_47")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.label_48 = QtWidgets.QLabel(self.scigrpbox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.formLayout_8.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_48)
        self.sciact = QtWidgets.QLineEdit(self.scigrpbox)
        self.sciact.setMaximumSize(QtCore.QSize(78, 20))
        self.sciact.setObjectName("sciact")
        reg_ex = QtCore.QRegExp("[0-9]+.?[0-9]{,2}")
        input_validator = QtGui.QRegExpValidator(reg_ex, self.sciact)
        self.sciact.setValidator(input_validator)
        self.formLayout_8.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.sciact)
        self.formLayout_9.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout_8)
        self.scitable = QtWidgets.QTableWidget(self.scigrpbox)
        self.scitable.setMinimumSize(QtCore.QSize(729, 600))
        self.scitable.setMaximumSize(QtCore.QSize(729, 619))
        self.scitable.setObjectName("scitable")
        self.scitable.setColumnCount(4)
        self.scitable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.scitable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.scitable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.scitable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.scitable.setHorizontalHeaderItem(3, item)
        self.scitable.horizontalHeader().setDefaultSectionSize(175)
        self.scitable.verticalHeader().setCascadingSectionResizes(False)
        self.scitable.verticalHeader().setDefaultSectionSize(46)
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.scitable)
        self.scicalculate = QtWidgets.QPushButton(self.scigrpbox)
        self.scicalculate.setObjectName("scicalculate")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.scicalculate)
       # self.sciupdate = QtWidgets.QPushButton(self.scigrpbox)
       # self.sciupdate.setMinimumSize(QtCore.QSize(93, 28))
       # self.sciupdate.setMaximumSize(QtCore.QSize(200, 28))
       # self.sciupdate.setObjectName("sciupdate")
       # self.scicheckBox = QtWidgets.QCheckBox(self.scigrpbox)
       # self.scicheckBox.setGeometry(QtCore.QRect(10, 530, 521, 20))
       # self.scicheckBox.setObjectName("scicheckBox")
       # self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.sciupdate)
        self.sciresult = QtWidgets.QTextBrowser(self.scigrpbox)
        self.sciresult.setMaximumSize(QtCore.QSize(621, 101))
        self.sciresult.setObjectName("sciresult")
        self.sciresult.setFontPointSize(12)
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.sciresult)
        self.verticalLayout_7.addWidget(self.scigrpbox)
        self.tabs.addTab(self.scitab, "")
        self.wltab = QtWidgets.QWidget()
        self.wltab.setObjectName("wltab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.wltab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.wlgrpbox = QtWidgets.QGroupBox(self.wltab)
        self.wlgrpbox.setTitle("")
        self.wlgrpbox.setObjectName("wlgrpbox")
        self.formLayout_11 = QtWidgets.QFormLayout(self.wlgrpbox)
        self.formLayout_11.setObjectName("formLayout_11")
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout_10.setObjectName("formLayout_10")
        self.wlname = QtWidgets.QLineEdit(self.wlgrpbox)
        self.wlname.setMaximumSize(QtCore.QSize(78, 20))
        self.wlname.setObjectName("wlname")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.wlname)
        self.label_49 = QtWidgets.QLabel(self.wlgrpbox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.formLayout_10.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_49)
        self.wlexp = QtWidgets.QLineEdit(self.wlgrpbox)
        self.wlexp.setMaximumSize(QtCore.QSize(78, 20))
        self.wlexp.setObjectName("wlexp")
        reg_ex = QtCore.QRegExp("[0-9]+.?[0-9]{,2}")
        input_validator = QtGui.QRegExpValidator(reg_ex, self.wlexp)
        self.wlexp.setValidator(input_validator)
        self.formLayout_10.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.wlexp)
        self.wladdnew = QtWidgets.QPushButton(self.wlgrpbox)
        self.wladdnew.setMaximumSize(QtCore.QSize(75, 23))
        self.wladdnew.setObjectName("wladdnew")
        self.formLayout_10.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.wladdnew)
        #self.wldel = QtWidgets.QPushButton(self.wlgrpbox)
        #self.wldel.setMaximumSize(QtCore.QSize(75, 23))
        #self.wldel.setObjectName("wldel")
        #self.formLayout_10.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.wldel)
        self.wldate = QtWidgets.QDateEdit(self.wlgrpbox)
        self.wldate.setCalendarPopup(True)
        self.wldate.setMaximumSize(QtCore.QSize(95, 22))
        self.wldate.setMinimumDate(QtCore.QDate.currentDate())
        self.wldate.setObjectName("wldate")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.wldate)
        self.label_50 = QtWidgets.QLabel(self.wlgrpbox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_50)
        self.label_51 = QtWidgets.QLabel(self.wlgrpbox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_51.setFont(font)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setWordWrap(True)
        self.label_51.setObjectName("label_51")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_51)
        self.label_52 = QtWidgets.QLabel(self.wlgrpbox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.formLayout_10.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_52)
        self.wlact = QtWidgets.QLineEdit(self.wlgrpbox)
        self.wlact.setMaximumSize(QtCore.QSize(78, 20))
        self.wlact.setObjectName("wlact")
        reg_ex = QtCore.QRegExp("[0-9]+.?[0-9]{,2}")
        input_validator = QtGui.QRegExpValidator(reg_ex, self.wlact)
        self.wlact.setValidator(input_validator)
        self.formLayout_10.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.wlact)
        self.formLayout_11.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout_10)
        self.wltable = QtWidgets.QTableWidget(self.wlgrpbox)
        self.wltable.setMinimumSize(QtCore.QSize(729, 600))
        self.wltable.setMaximumSize(QtCore.QSize(729, 619))
        self.wltable.setObjectName("wltable")
        self.wltable.setColumnCount(4)
        self.wltable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.wltable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.wltable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.wltable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.wltable.setHorizontalHeaderItem(3, item)
        self.wltable.horizontalHeader().setDefaultSectionSize(175)
        self.wltable.verticalHeader().setCascadingSectionResizes(False)
        self.wltable.verticalHeader().setDefaultSectionSize(46)
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.wltable)
        self.wlcalculate = QtWidgets.QPushButton(self.wlgrpbox)
        self.wlcalculate.setObjectName("wlcalculate")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.wlcalculate)
       #self.wlupdate = QtWidgets.QPushButton(self.wlgrpbox)
       #self.wlupdate.setMinimumSize(QtCore.QSize(93, 28))
       #self.wlupdate.setMaximumSize(QtCore.QSize(200, 28))
       #self.wlupdate.setObjectName("wlupdate")
       #self.wlcheckBox = QtWidgets.QCheckBox(self.wlgrpbox)
       #self.wlcheckBox.setGeometry(QtCore.QRect(10, 530, 521, 20))
       #self.wlcheckBox.setObjectName("wlcheckBox")
       #self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.wlupdate)
        self.wlresult = QtWidgets.QTextBrowser(self.wlgrpbox)
        self.wlresult.setMaximumSize(QtCore.QSize(621, 101))
        self.wlresult.setObjectName("wlresult")
        self.wlresult.setFontPointSize(12)
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.wlresult)
        self.verticalLayout_5.addWidget(self.wlgrpbox)
        self.tabs.addTab(self.wltab, "")
        self.enltab = QtWidgets.QWidget()
        self.enltab.setObjectName("enltab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.enltab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.enlgrpbox = QtWidgets.QGroupBox(self.enltab)
        self.enlgrpbox.setTitle("")
        self.enlgrpbox.setObjectName("enlgrpbox")
        self.formLayout_13 = QtWidgets.QFormLayout(self.enlgrpbox)
        self.formLayout_13.setObjectName("formLayout_13")
        self.formLayout_12 = QtWidgets.QFormLayout()
        self.formLayout_12.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout_12.setObjectName("formLayout_12")
        self.enlname = QtWidgets.QLineEdit(self.enlgrpbox)
        self.enlname.setMaximumSize(QtCore.QSize(78, 20))
        self.enlname.setObjectName("enlname")
        self.formLayout_12.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.enlname)
        self.label_53 = QtWidgets.QLabel(self.enlgrpbox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.formLayout_12.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_53)
        self.enlexp = QtWidgets.QLineEdit(self.enlgrpbox)
        self.enlexp.setMaximumSize(QtCore.QSize(78, 20))
        self.enlexp.setObjectName("enlexp")
        reg_ex = QtCore.QRegExp("[0-9]+.?[0-9]{,2}")
        input_validator = QtGui.QRegExpValidator(reg_ex, self.enlexp)
        self.enlexp.setValidator(input_validator)
        self.formLayout_12.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.enlexp)
        self.enladdnew = QtWidgets.QPushButton(self.enlgrpbox)
        self.enladdnew.setMaximumSize(QtCore.QSize(75, 23))
        self.enladdnew.setObjectName("enladdnew")
        self.formLayout_12.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.enladdnew)
       #self.enldel = QtWidgets.QPushButton(self.enlgrpbox)
       #self.enldel.setMaximumSize(QtCore.QSize(75, 23))
       #self.enldel.setObjectName("enldel")
       #self.formLayout_12.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.enldel)
        self.enldate = QtWidgets.QDateEdit(self.enlgrpbox)
        self.enldate.setCalendarPopup(True)
        self.enldate.setMaximumSize(QtCore.QSize(95, 22))
        self.enldate.setMinimumDate(QtCore.QDate.currentDate())
        self.enldate.setObjectName("enldate")
        self.formLayout_12.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.enldate)
        self.label_54 = QtWidgets.QLabel(self.enlgrpbox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.formLayout_12.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_54)
        self.label_55 = QtWidgets.QLabel(self.enlgrpbox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_55.setFont(font)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setWordWrap(True)
        self.label_55.setObjectName("label_55")
        self.formLayout_12.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_55)
        self.label_56 = QtWidgets.QLabel(self.enlgrpbox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.formLayout_12.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_56)
        self.enlact = QtWidgets.QLineEdit(self.enlgrpbox)
        self.enlact.setMaximumSize(QtCore.QSize(78, 20))
        self.enlact.setObjectName("enlact")
        reg_ex = QtCore.QRegExp("[0-9]+.?[0-9]{,2}")
        input_validator = QtGui.QRegExpValidator(reg_ex, self.enlact)
        self.enlact.setValidator(input_validator)
        self.formLayout_12.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.enlact)
        self.formLayout_13.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout_12)
        self.enltable = QtWidgets.QTableWidget(self.enlgrpbox)
        self.enltable.setMinimumSize(QtCore.QSize(729, 600))
        self.enltable.setMaximumSize(QtCore.QSize(729, 619))
        self.enltable.setObjectName("enltable")
        self.enltable.setColumnCount(4)
        self.enltable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.enltable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.enltable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.enltable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.enltable.setHorizontalHeaderItem(3, item)
        self.enltable.horizontalHeader().setDefaultSectionSize(175)
        self.enltable.verticalHeader().setCascadingSectionResizes(False)
        self.enltable.verticalHeader().setDefaultSectionSize(46)
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.enltable)
        self.enlcalculate = QtWidgets.QPushButton(self.enlgrpbox)
        self.enlcalculate.setObjectName("enlcalculate")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.enlcalculate)
        #self.enlupdate = QtWidgets.QPushButton(self.enlgrpbox)
        #self.enlupdate.setMinimumSize(QtCore.QSize(93, 28))
        #self.enlupdate.setMaximumSize(QtCore.QSize(200, 28))
        #self.enlupdate.setObjectName("enlupdate")
        #self.enlcheckBox = QtWidgets.QCheckBox(self.enlgrpbox)
        #self.enlcheckBox.setGeometry(QtCore.QRect(10, 530, 521, 20))
        #self.enlcheckBox.setObjectName("enlcheckBox")
        #self.formLayout_13.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.enlupdate)
        self.enlresult = QtWidgets.QTextBrowser(self.enlgrpbox)
        self.enlresult.setMaximumSize(QtCore.QSize(621, 101))
        self.enlresult.setObjectName("enlresult")
        self.enlresult.setFontPointSize(12)
        self.formLayout_13.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.enlresult)
        self.verticalLayout_4.addWidget(self.enlgrpbox)
        self.tabs.addTab(self.enltab, "")
        self.verticalLayout.addWidget(self.tabs)
        MainWindow.setCentralWidget(self.centralwidget)
        #self.menubar = QtWidgets.QMenuBar(MainWindow)
        #self.menubar.setGeometry(QtCore.QRect(0, 0, 1044, 26))
        #self.menubar.setObjectName("menubar")
        #self.menuFile = QtWidgets.QMenu(self.menubar)
        #self.menuFile.setObjectName("menuFile")
        #MainWindow.setMenuBar(self.menubar)
        #self.statusbar = QtWidgets.QStatusBar(MainWindow)
        #self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)
        #self.actionSave = QtWidgets.QAction(MainWindow)
        #self.actionSave.setObjectName("actionSave")
        #self.actionQuit = QtWidgets.QAction(MainWindow)
        #self.actionQuit.setObjectName("actionQuit")
        #self.actionUpdate = QtWidgets.QAction(MainWindow)
        #self.actionUpdate.setObjectName("actionUpdate")
        #self.menuFile.addAction(self.actionSave)
        #self.menuFile.addAction(self.actionQuit)
        #self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Accommodation Calculator"))     
        self.stunamelbl.setText(_translate("MainWindow", "Student Name (New Entry)"))
        self.label.setText(_translate("MainWindow", "Save ONLY after entering data. Refer to readme."))
        self.pushButton_2.setText(_translate("MainWindow", "Save"))
        self.stunamelbl_2.setText(_translate("MainWindow", "Student Name (Existing Entry)"))
        self.pushButton.setText(_translate("MainWindow", "Load "))
        self.pushButton_3.setText(_translate("MainWindow", "Save Updated"))
        self.elaacclbl.setText(_translate("MainWindow", "ELA Accommodation"))
        self.mathacclbl.setText(_translate("MainWindow", "Math Accommodation"))
        self.sciacclbl.setText(_translate("MainWindow", "Science Accommodation"))
        self.ssacclbl.setText(_translate("MainWindow", "Social Studies Accommodation"))
        self.wlacclbl.setText(_translate("MainWindow", "World Languages Accommodation"))
        self.enlacclbl.setText(_translate("MainWindow", "ENL Accommodation"))
        #self.deleterec.setText(_translate("MainWindow", "DELETE RECORD"))
        #self.sure.setText(_translate("MainWindow", "Are you sure you want to delete record completely?"))
        #self.deleterecordchk.setText(_translate("MainWindow", "Check this box to activate delete key"))
        self.tabs.setTabText(self.tabs.indexOf(self.StudentInfo), _translate("MainWindow", "Student Summary"))
        self.label_35.setText(_translate("MainWindow", "Expected Time"))
        self.elaaddnew.setText(_translate("MainWindow", "Add New"))
        #self.elacheckBox.setWordWrap(True)
        #self.elacheckBox.setText(_translate("MainWindow", "Enable this check box to update"))
        #self.mathcheckBox.setText(_translate("MainWindow", "Enable this check box to update"))
        #self.sscheckBox.setText(_translate("MainWindow", "Enable this check box to update"))
        #self.scicheckBox.setText(_translate("MainWindow", "Enable this check box to update"))
        #self.wlcheckBox.setText(_translate("MainWindow", "Enable this check box to update"))
        #self.enlcheckBox.setText(_translate("MainWindow", "Enable this check box to update"))
        #self.eladel.setText(_translate("MainWindow", "Delete Last"))
        #self.mathdel.setText(_translate("MainWindow", "Delete Last"))
        #self.ssdel.setText(_translate("MainWindow", "Delete Last"))
        #self.scidel.setText(_translate("MainWindow", "Delete Last"))
        #self.wldel.setText(_translate("MainWindow", "Delete Last"))
        #self.enldel.setText(_translate("MainWindow", "Delete Last"))
        self.label_33.setText(_translate("MainWindow", "Date of Test"))
        self.label_34.setText(_translate("MainWindow", "Name/Number of test"))
        self.label_36.setText(_translate("MainWindow", "Actual Time"))
        item = self.elatable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.elatable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Test Number/Name"))
        item = self.elatable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Expected Score"))
        item = self.elatable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Actual Score"))
        self.elacalculate.setText(_translate("MainWindow", "Calculate"))
        #self.elaupdate.setText(_translate("MainWindow", "Update"))
        #self.mathupdate.setText(_translate("MainWindow", "Update"))
        #self.ssupdate.setText(_translate("MainWindow", "Update"))
        #self.sciupdate.setText(_translate("MainWindow", "Update"))
        #self.wlupdate.setText(_translate("MainWindow", "Update"))
        #self.enlupdate.setText(_translate("MainWindow", "Update"))
        self.tabs.setTabText(self.tabs.indexOf(self.elatab), _translate("MainWindow", "ELA"))
        self.label_37.setText(_translate("MainWindow", "Expected Time"))
        self.mathaddnew.setText(_translate("MainWindow", "Add New"))
        self.label_38.setText(_translate("MainWindow", "Date of Test"))
        self.label_39.setText(_translate("MainWindow", "Name/Number of test"))
        self.label_40.setText(_translate("MainWindow", "Actual Time"))
        item = self.mathtable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.mathtable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Test Number/Name"))
        item = self.mathtable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Expected Score"))
        item = self.mathtable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Actual Score"))
        self.mathcalculate.setText(_translate("MainWindow", "Calculate"))
        self.tabs.setTabText(self.tabs.indexOf(self.mathtab), _translate("MainWindow", "Math"))
        self.label_41.setText(_translate("MainWindow", "Expected Time"))
        self.ssaddnew.setText(_translate("MainWindow", "Add New"))
        self.label_42.setText(_translate("MainWindow", "Date of Test"))
        self.label_43.setText(_translate("MainWindow", "Name/Number of test"))
        self.label_44.setText(_translate("MainWindow", "Actual Time"))
        item = self.sstable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.sstable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Test Number/Name"))
        item = self.sstable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Expected Score"))
        item = self.sstable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Actual Score"))
        self.sscalculate.setText(_translate("MainWindow", "Calculate"))
        self.tabs.setTabText(self.tabs.indexOf(self.sstab), _translate("MainWindow", "Social Studies"))
        self.label_45.setText(_translate("MainWindow", "Expected Time"))
        self.sciaddnew.setText(_translate("MainWindow", "Add New"))
        self.label_46.setText(_translate("MainWindow", "Date of Test"))
        self.label_47.setText(_translate("MainWindow", "Name/Number of test"))
        self.label_48.setText(_translate("MainWindow", "Actual Time"))
        item = self.scitable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.scitable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Test Number/Name"))
        item = self.scitable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Expected Score"))
        item = self.scitable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Actual Score"))
        self.scicalculate.setText(_translate("MainWindow", "Calculate"))
        self.tabs.setTabText(self.tabs.indexOf(self.scitab), _translate("MainWindow", "Science"))
        self.label_49.setText(_translate("MainWindow", "Expected Time"))
        self.wladdnew.setText(_translate("MainWindow", "Add New"))
        self.label_50.setText(_translate("MainWindow", "Date of Test"))
        self.label_51.setText(_translate("MainWindow", "Name/Number of test"))
        self.label_52.setText(_translate("MainWindow", "Actual Time"))
        item = self.wltable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.wltable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Test Number/Name"))
        item = self.wltable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Expected Score"))
        item = self.wltable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Actual Score"))
        self.wlcalculate.setText(_translate("MainWindow", "Calculate"))
        self.tabs.setTabText(self.tabs.indexOf(self.wltab), _translate("MainWindow", "World Languages"))
        self.label_53.setText(_translate("MainWindow", "Expected Time"))
        self.enladdnew.setText(_translate("MainWindow", "Add New"))
        self.label_54.setText(_translate("MainWindow", "Date of Test"))
        self.label_55.setText(_translate("MainWindow", "Name/Number of test"))
        self.label_56.setText(_translate("MainWindow", "Actual Time"))
        item = self.enltable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.enltable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Test Number/Name"))
        item = self.enltable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Expected Score"))
        item = self.enltable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Actual Score"))
        self.enlcalculate.setText(_translate("MainWindow", "Calculate"))
        self.tabs.setTabText(self.tabs.indexOf(self.enltab), _translate("MainWindow", "ENL"))
        #self.menuFile.setTitle(_translate("MainWindow", "File"))
        #self.actionSave.setText(_translate("MainWindow", "Save"))
        #self.actionQuit.setText(_translate("MainWindow", "Quit"))


